/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublishSuccessRouteImport } from './routes/publish-success'
import { Route as TabsHealthRouteImport } from './routes/_tabs.health'
import { Route as TabsHomeRouteImport } from './routes/_tabs.home'
import { Route as TabsListingRouteImport } from './routes/_tabs.listing'
import { Route as TabsProfileRouteImport } from './routes/_tabs.profile'
import { Route as TabsQaRouteImport } from './routes/_tabs.qa'
import { Route as ListingPreviewRouteImport } from './routes/listing.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishSuccessRoute = PublishSuccessRouteImport.update({
  id: '/publish-success',
  path: '/publish-success',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsHealthRoute = TabsHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => TabsRoute,
} as any)
const TabsHomeRoute = TabsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TabsRoute,
} as any)
const TabsListingRoute = TabsListingRouteImport.update({
  id: '/listing',
  path: '/listing',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProfileRoute = TabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsQaRoute = TabsQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => TabsRoute,
} as any)
const ListingPreviewRoute = ListingPreviewRouteImport.update({
  id: '/listing/preview',
  path: '/listing/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/publish-success': typeof PublishSuccessRoute
  '/health': typeof TabsHealthRoute
  '/home': typeof TabsHomeRoute
  '/listing': typeof TabsListingRoute
  '/profile': typeof TabsProfileRoute
  '/qa': typeof TabsQaRoute
  '/listing/preview': typeof ListingPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/publish-success': typeof PublishSuccessRoute
  '/health': typeof TabsHealthRoute
  '/home': typeof TabsHomeRoute
  '/listing': typeof TabsListingRoute
  '/profile': typeof TabsProfileRoute
  '/qa': typeof TabsQaRoute
  '/listing/preview': typeof ListingPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/auth': typeof AuthRoute
  '/publish-success': typeof PublishSuccessRoute
  '/_tabs/health': typeof TabsHealthRoute
  '/_tabs/home': typeof TabsHomeRoute
  '/_tabs/listing': typeof TabsListingRoute
  '/_tabs/profile': typeof TabsProfileRoute
  '/_tabs/qa': typeof TabsQaRoute
  '/listing/preview': typeof ListingPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/publish-success'
    | '/health'
    | '/home'
    | '/listing'
    | '/profile'
    | '/qa'
    | '/listing/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/publish-success'
    | '/health'
    | '/home'
    | '/listing'
    | '/profile'
    | '/qa'
    | '/listing/preview'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/auth'
    | '/publish-success'
    | '/_tabs/health'
    | '/_tabs/home'
    | '/_tabs/listing'
    | '/_tabs/profile'
    | '/_tabs/qa'
    | '/listing/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  AuthRoute: typeof AuthRoute
  PublishSuccessRoute: typeof PublishSuccessRoute
  ListingPreviewRoute: typeof ListingPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish-success': {
      id: '/publish-success'
      path: '/publish-success'
      fullPath: '/publish-success'
      preLoaderRoute: typeof PublishSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/health': {
      id: '/_tabs/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof TabsHealthRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/home': {
      id: '/_tabs/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof TabsHomeRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/listing': {
      id: '/_tabs/listing'
      path: '/listing'
      fullPath: '/listing'
      preLoaderRoute: typeof TabsListingRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/profile': {
      id: '/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof TabsProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/qa': {
      id: '/_tabs/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof TabsQaRouteImport
      parentRoute: typeof TabsRoute
    }
    '/listing/preview': {
      id: '/listing/preview'
      path: '/listing/preview'
      fullPath: '/listing/preview'
      preLoaderRoute: typeof ListingPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TabsRouteChildren {
  TabsHealthRoute: typeof TabsHealthRoute
  TabsHomeRoute: typeof TabsHomeRoute
  TabsListingRoute: typeof TabsListingRoute
  TabsProfileRoute: typeof TabsProfileRoute
  TabsQaRoute: typeof TabsQaRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsHealthRoute: TabsHealthRoute,
  TabsHomeRoute: TabsHomeRoute,
  TabsListingRoute: TabsListingRoute,
  TabsProfileRoute: TabsProfileRoute,
  TabsQaRoute: TabsQaRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  AuthRoute: AuthRoute,
  PublishSuccessRoute: PublishSuccessRoute,
  ListingPreviewRoute: ListingPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
